-- 코드를 작성해주세요

SELECT b.YEAR, ROUND(AVG(b.PM_VAL1), 2) AS 'PM10', ROUND(AVG(b.PM_VAL2), 2) AS 'PM2.5'
FROM (
        SELECT YEAR(a.YM) AS 'YEAR', a.PM_VAL1, a.PM_VAL2
        FROM AIR_POLLUTION a
        WHERE LOCATION2 = '수원') b
GROUP BY YEAR
ORDER BY YEAR