-- 코드를 입력하세요
SELECT PRODUCT_CODE, (SALES_AMOUNT * PRICE) AS SALES
FROM PRODUCT P JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
                   FROM OFFLINE_SALE
                   GROUP BY PRODUCT_ID) S ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE