-- 코드를 작성해주세요
SELECT CONCAT(QD.QUARTER, 'Q') AS QUARTER, COUNT(QD.ID) AS ECOLI_COUNT
FROM (SELECT QUARTER(DIFFERENTIATION_DATE) AS QUARTER, ID
      FROM ECOLI_DATA
     ) AS QD
GROUP BY QUARTER
ORDER BY QUARTER