-- 코드를 입력하세요
SELECT a.FLAVOR
FROM (
    SELECT f.FLAVOR, f.TOTAL_ORDER + j.TOTAL_ORDER AS 'SUM1'
    FROM FIRST_HALF f JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
        FROM JULY
        GROUP BY FLAVOR) j ON f.FLAVOR = j.FLAVOR
        ORDER BY SUM1 DESC
    ) a
LIMIT 3