-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) AS 'YEAR', b.MAX - a.SIZE_OF_COLONY AS 'YEAR_DEV', ID
FROM ECOLI_DATA a JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS 'MAX'
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR, YEAR_DEV