-- 코드를 작성해주세요
SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO                   
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
    )
ORDER BY FI.ID